### ISSUE TITLE
Feature: Upgrade sentry gems to 7.x and lift the 6.x pin

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#1090]
### Which service is this about?

Right to Know

### What problem are you trying to solve?

The theme is pinned to the sentry 6.x line as a stopgap, so we are not getting 7.x. The pin was added to unblock a broken production deploy, not because 6.x is where we want to stay.

[sentry-ruby 7.0.0](https://github.com/getsentry/sentry-ruby/blob/master/CHANGELOG.md) was released on 2026-09-01. The three sentry gems in `Gemfile.theme` were unpinned and are not covered by the host Alaveteli `Gemfile.lock` (they are merged in at deploy time via `eval_gemfile`), so the `cap production deploy` on 2026-09-03 resolved 7.0.0 fresh and aborted at `deploy:assets:precompile`:

```
NoMethodError: undefined method 'enable_logs=' for an instance of Sentry::Configuration
/srv/www/production/releases/.../lib/themes/righttoknow/lib/sentry_config.rb:27
```

Production never switched release, so there was no outage, but the deploy could not complete until the gems were pinned to `~> 6.7`.

### What would you like to happen?

Upgrade to sentry 7.x deliberately, on staging first, and lift the pin. 7.0.0 is a breaking release and changes more than the one method that broke us. From the upstream changelog:

- **`enable_logs` is removed.** Logs are on by default, and `sentry-rails` turns on automatic structured logging from Rails. `lib/sentry_config.rb:27` needs the line deleted, and we need to decide whether we want Rails structured logging at all, or `config.rails.structured_logging.enabled = false` ([#3053](https://github.com/getsentry/sentry-ruby/pull/3053)).
- **`enable_metrics` is removed and metrics are on by default** ([#3061](https://github.com/getsentry/sentry-ruby/pull/3061)). We have not opted into metrics before, so this is new data leaving the servers and new quota use.
- **`send_default_pii` is deprecated in favour of a granular `data_collection` config.** It still works in 7.0 and is removed in 8.0. `lib/sentry_config.rb` currently sets `send_default_pii = true`, so this one deserves a proper look rather than a mechanical port: Right to Know handles FOI correspondence, and `data_collection` controls exactly which user info, cookies, headers, request bodies, query params and database query data get attached to events. Worth deciding what we actually want to collect under the Australian Privacy Principles rather than inheriting a default.
- **`config.otlp.setup_otlp_traces_exporter` and `config.otlp.setup_propagator` now default to false** ([#3063](https://github.com/getsentry/sentry-ruby/pull/3063)).

Suggested order of work: bump the pin on a branch, deploy to staging, confirm errors and traces still arrive in the correct Sentry environment, review what the new `data_collection` defaults send, then deploy to production and lift or widen the pin.

### Alternatives you've considered

Stay on 6.x indefinitely. The pin makes deploys reproducible so nothing is currently broken, but 6.x will stop getting fixes and the `send_default_pii` removal in 8.0 is coming either way, so the migration only gets larger.

Unpin entirely and take whatever resolves. That is what caused this, so no.

### Anything else?

The underlying deploy fragility is fixed by the pin itself: `Gemfile.theme` gems are resolved fresh on every deploy and nothing else constrains them, so any unpinned gem there can break a deploy the day upstream ships a major. Worth keeping in mind when adding gems to that file.

Related: #1004 (the original Sentry integration).

Assisted-by: Claude Code:claude-opus-5
